name: CI/CD Modelo Iris

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    name: Pruebas rápidas de endpoints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Instalar dependencias
        run: pip install -r requirements.txt
      - name: Lanzar API en background
        run: |
          python api.py &
          echo $! > api.pid
          sleep 5
      - name: Probar /health
        run: |
          curl -sSf http://127.0.0.1:5000/health | tee health.json
          grep '"status"' health.json
      - name: Probar /predict
        run: |
          curl -sSf -X POST http://127.0.0.1:5000/predict \
            -H 'Content-Type: application/json' \
            -d '{"features": [5.1, 3.5, 1.4, 0.2]}' | tee predict.json
          grep '"prediction"' predict.json
      - name: Apagar API
        if: always()
        run: |
          kill $(cat api.pid) || true

  build-and-push:
    name: Construir y publicar imagen
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Construir y subir
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/iris-ml-api:latest,${{ secrets.DOCKERHUB_USERNAME }}/iris-ml-api:${{ github.sha }}
      - name: Mostrar digest
        run: |
          echo "Digest: ${{ steps.build.outputs.digest }}" || echo "Digest no disponible"